/**
 * Mirror every contract fixture under tests/fixtures/** into a TypeScript
 * module whose object literal is checked with `satisfies <SDK type>`.
 *
 * Why a mirror: a JSON import widens `"moderate"` to `string`, so
 * `satisfies EvaluateResponse` on the imported value cannot check enum
 * literals. A fresh object literal in a .ts file gets contextual typing,
 * literal checks and excess-property checks, which is exactly the contract
 * we want: every key on the wire is typed, every enum value is in range.
 *
 * tests/contract/fixtures.test.ts asserts each generated module deep-equals
 * the JSON it came from, so a stale mirror fails `pnpm test`.
 *
 * Run: pnpm generate:fixtures
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const FIXTURES = join(ROOT, 'tests', 'fixtures');
const OUT = join(ROOT, 'tests', 'contract', 'generated');

/** Folders that are not response bodies (signed webhook envelopes, raw headers). */
const SKIP_FOLDERS = new Set(['webhooks', 'headers']);

interface FixtureBinding {
  /** Exported SDK type the fixture must satisfy. */
  type: string;
  /**
   * API fix id when the fixture was captured before that fix deployed. The
   * check then runs against PendingApiFix<T> (every key optional, unknown
   * keys still rejected). Remove the entry after regenerating the fixture.
   */
  pending?: string;
}

/**
 * folder/file -> SDK type. A fixture without an entry aborts generation so a
 * new capture cannot land untyped.
 */
const BINDINGS: Record<string, FixtureBinding> = {
  'evaluate/auth.benign.json': { type: 'EvaluateResponse' },
  'evaluate/try.gb.json': { type: 'EvaluateResponse' },
  'evaluate/try.us.json': { type: 'EvaluateResponse' },
  'evaluate/try.gb.no-resources.json': { type: 'EvaluateResponse' },
  'evaluate/try.gb.text.json': { type: 'EvaluateResponse' },

  'oversight/auth.fast.json': { type: 'OversightAnalyzeResponse' },
  'oversight/try.fast.json': { type: 'OversightDemoAnalyzeResponse' },
  'oversight/try.full.json': { type: 'OversightDemoAnalyzeResponse' },

  'ocular/auth.json': { type: 'OcularResponse' },
  'ocular/try.json': { type: 'OcularDemoResponse' },
  'ocular/auth.per-turn.json': { type: 'OcularResponse' },

  'signpost/auth.gb.json': { type: 'SignpostResponse' },
  'signpost/try.smart.json': { type: 'SignpostSmartResponse' },
  'signpost/search.auth.json': { type: 'SignpostSearchResponse' },
  'signpost/search.auth.mixed-contacts.json': { type: 'SignpostSearchResponse' },
  'signpost/countries.json': { type: 'SignpostCountriesResponse' },
  'signpost/detect-country.miss.json': { type: 'DetectCountryResponse' },
  'signpost/by-id.json': { type: 'SignpostByIdResponse' },

  // Captured 2026-09-03 before API fix A-5 (billing.ts:152-175,308-349); the
  // fields that fix adds are typed optional until it deploys, so these check
  // against the real types.
  'billing/balance.json': { type: 'BillingBalanceResponse' },
  'billing/usage.json': { type: 'BillingUsageResponse' },
  'billing/pricing.json': { type: 'BillingPricingResponse' },

  'errors/400.evaluate-empty.json': { type: 'ApiErrorBody' },
  'errors/400.evaluate-role.json': { type: 'ApiErrorBody' },
  'errors/400.signpost-scope.json': { type: 'ApiErrorBody' },
  'errors/401.missing-auth.json': { type: 'ApiErrorBody' },
  'errors/404.signpost-id.json': { type: 'ApiErrorBody' },
  'errors/413.payload-too-large.json': { type: 'ApiErrorBody' },
};

/** `evaluate/auth.benign.json` -> `evaluate.auth.benign` (module basename). */
export function moduleNameFor(relPath: string): string {
  return relPath.replace(/\.json$/, '').replace(/\//g, '.');
}

export function listFixtures(): string[] {
  const out: string[] = [];
  for (const folder of readdirSync(FIXTURES, { withFileTypes: true })) {
    if (!folder.isDirectory() || SKIP_FOLDERS.has(folder.name)) continue;
    for (const file of readdirSync(join(FIXTURES, folder.name))) {
      if (file.endsWith('.json')) out.push(`${folder.name}/${file}`);
    }
  }
  return out.sort();
}

function render(relPath: string, binding: FixtureBinding, json: unknown): string {
  const literal = JSON.stringify(json, null, 2);
  const lines = [
    `// GENERATED by scripts/generate-fixture-modules.ts from tests/fixtures/${relPath}.`,
    '// Do not edit. Run `pnpm generate:fixtures` after the fixture changes.',
    `import type { ${binding.type} } from '../../../src/index.js';`,
  ];
  if (binding.pending) {
    lines.push(`import type { PendingApiFix } from '../pending.js';`);
    lines.push('');
    lines.push(
      `// Captured before API fix ${binding.pending} deployed, so the fields that fix adds are`,
      `// absent. Checked against PendingApiFix<${binding.type}> until the fixture is recaptured.`
    );
    lines.push(`export default ${literal} satisfies PendingApiFix<${binding.type}>;`);
  } else {
    lines.push('');
    lines.push(`export default ${literal} satisfies ${binding.type};`);
  }
  return lines.join('\n') + '\n';
}

function main(): void {
  const fixtures = listFixtures();
  const unknown = fixtures.filter((f) => !BINDINGS[f]);
  if (unknown.length) {
    throw new Error(`No type binding for fixture(s): ${unknown.join(', ')}`);
  }
  const stale = Object.keys(BINDINGS).filter((k) => !fixtures.includes(k));
  if (stale.length) {
    throw new Error(`Binding(s) without a fixture: ${stale.join(', ')}`);
  }

  if (existsSync(OUT)) rmSync(OUT, { recursive: true });
  mkdirSync(OUT, { recursive: true });

  for (const rel of fixtures) {
    const json = JSON.parse(readFileSync(join(FIXTURES, rel), 'utf8')) as unknown;
    const target = join(OUT, `${moduleNameFor(rel)}.ts`);
    writeFileSync(target, render(rel, BINDINGS[rel], json));
    console.log(`wrote ${basename(target)}`);
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
