/**
 * Generate the Oversight behavior taxonomy unions from the API source.
 *
 * Reads ../api/lib/prompts/content/oversight/taxonomy.ts (override the api
 * checkout with NOPE_API_DIR) as text, parses the `BehaviorCategory` union
 * and the `BEHAVIOR_CODES` object literal, and writes
 * src/generated/oversight-taxonomy.ts. The API's TypeScript is never
 * imported, so the SDK build has no dependency on the api repo.
 *
 * Run: pnpm generate:taxonomy
 * Verified by: tests/unit/taxonomy.test.ts (91 codes, 14 categories).
 */

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const API_DIR = resolve(ROOT, process.env.NOPE_API_DIR ?? '../api');
const OUT_DIR = join(ROOT, 'src', 'generated');

const IDENT = /^[a-z_]+$/;

function apiRevision(): string {
  try {
    return execSync('git rev-parse --short HEAD', { cwd: API_DIR, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return 'unknown';
  }
}

function quoted(list: string): string[] {
  return [...list.matchAll(/'([a-z_]+)'/g)].map((m) => m[1]);
}

/** Parse `export type BehaviorCategory = | 'a' | 'b' ...;` */
export function parseCategoryUnion(source: string): string[] {
  const m = source.match(/export type BehaviorCategory =([\s\S]*?);/);
  if (!m) throw new Error('BehaviorCategory union not found');
  const values = quoted(m[1]);
  if (values.length === 0) throw new Error('BehaviorCategory union is empty');
  return values;
}

/** Parse `export const BEHAVIOR_CODES = { category: ['code', ...], ... } as const;` */
export function parseBehaviorCodes(source: string): Record<string, string[]> {
  const start = source.indexOf('export const BEHAVIOR_CODES = {');
  if (start === -1) throw new Error('BEHAVIOR_CODES not found');
  const end = source.indexOf('} as const;', start);
  if (end === -1) throw new Error('BEHAVIOR_CODES has no `} as const;` terminator');
  const block = source.slice(start, end);
  const out: Record<string, string[]> = {};
  for (const m of block.matchAll(/([a-z_]+):\s*\[([^\]]*)\]/g)) {
    out[m[1]] = quoted(m[2]);
  }
  if (Object.keys(out).length === 0) throw new Error('BEHAVIOR_CODES parsed to nothing');
  return out;
}

export interface Taxonomy {
  categories: string[];
  codesByCategory: Record<string, string[]>;
}

export function parseTaxonomy(source: string): Taxonomy {
  const categories = parseCategoryUnion(source);
  const codesByCategory = parseBehaviorCodes(source);

  const keys = Object.keys(codesByCategory);
  const missing = categories.filter((c) => !keys.includes(c));
  const extra = keys.filter((k) => !categories.includes(k));
  if (missing.length || extra.length) {
    throw new Error(`category mismatch: union lacks [${extra}] / codes lack [${missing}]`);
  }
  const all = Object.values(codesByCategory).flat();
  const dupes = all.filter((c, i) => all.indexOf(c) !== i);
  if (dupes.length) throw new Error(`duplicate behavior codes: ${dupes.join(', ')}`);
  for (const v of [...categories, ...all]) {
    if (!IDENT.test(v)) throw new Error(`unexpected identifier: ${v}`);
  }
  return { categories, codesByCategory };
}

export function renderOversight(t: Taxonomy, sourceRel: string, revision: string): string {
  const lines: string[] = [
    `// GENERATED by scripts/generate-taxonomy.ts from ${sourceRel} (api ${revision}).`,
    '// Do not edit. Run `pnpm generate:taxonomy` against a current api checkout.',
    '',
    '/** Oversight behavior codes grouped by category, in taxonomy order. */',
    'export const OVERSIGHT_BEHAVIOR_CODES_BY_CATEGORY = {',
  ];
  for (const cat of t.categories) {
    lines.push(`  ${cat}: [`);
    for (const code of t.codesByCategory[cat]) lines.push(`    '${code}',`);
    lines.push('  ],');
  }
  lines.push(
    '} as const;',
    '',
    '/** One of the Oversight behavior categories. */',
    'export type OversightBehaviorCategory = keyof typeof OVERSIGHT_BEHAVIOR_CODES_BY_CATEGORY;',
    '',
    '/** One of the Oversight behavior codes. */',
    'export type OversightBehaviorCode =',
    '  (typeof OVERSIGHT_BEHAVIOR_CODES_BY_CATEGORY)[OversightBehaviorCategory][number];',
    '',
    '/** Every category, in taxonomy order. */',
    'export const OVERSIGHT_BEHAVIOR_CATEGORIES: readonly OversightBehaviorCategory[] = [',
    ...t.categories.map((c) => `  '${c}',`),
    '];',
    '',
    '/** Every behavior code, in taxonomy order. */',
    'export const OVERSIGHT_BEHAVIOR_CODES: readonly OversightBehaviorCode[] = Object.values(',
    '  OVERSIGHT_BEHAVIOR_CODES_BY_CATEGORY',
    ').flat();',
    ''
  );
  return lines.join('\n');
}

/**
 * Parse the values of `export const <NAME> = { key: 'value', ... } as const;`
 * from api/lib/resources/classificationToScopes.ts (SERVICE_SCOPES, POPULATIONS).
 */
export function parseConstObjectValues(source: string, name: string): string[] {
  const start = source.indexOf(`export const ${name} = {`);
  if (start === -1) throw new Error(`${name} not found`);
  const end = source.indexOf('} as const;', start);
  if (end === -1) throw new Error(`${name} has no \`} as const;\` terminator`);
  const values = quoted(source.slice(start, end));
  if (values.length === 0) throw new Error(`${name} parsed to nothing`);
  const dupes = values.filter((v, i) => values.indexOf(v) !== i);
  if (dupes.length) throw new Error(`${name} has duplicate values: ${dupes.join(', ')}`);
  return values;
}

export function renderSignpost(scopes: string[], populations: string[], sourceRel: string, revision: string): string {
  const list = (values: string[]) => values.map((v) => `  '${v}',`);
  return [
    `// GENERATED by scripts/generate-taxonomy.ts from ${sourceRel} (api ${revision}).`,
    '// Do not edit. Run `pnpm generate:taxonomy` against a current api checkout.',
    '',
    '/** Service scopes accepted by the signpost `scopes` filter, in source order. */',
    'export const SERVICE_SCOPES = [',
    ...list(scopes),
    '] as const;',
    '',
    '/** One of the signpost service scopes (e.g. `suicide`, `domestic_violence`). */',
    'export type ServiceScope = (typeof SERVICE_SCOPES)[number];',
    '',
    '/** Populations accepted by the signpost `populations` filter, in source order. */',
    'export const POPULATIONS = [',
    ...list(populations),
    '] as const;',
    '',
    '/** One of the signpost populations (e.g. `youth`, `veterans`, `lgbtq`). */',
    'export type Population = (typeof POPULATIONS)[number];',
    '',
  ].join('\n');
}

function main(): void {
  const revision = apiRevision();
  mkdirSync(OUT_DIR, { recursive: true });

  const taxonomyRel = 'api/lib/prompts/content/oversight/taxonomy.ts';
  const taxonomySrc = join(API_DIR, 'lib', 'prompts', 'content', 'oversight', 'taxonomy.ts');
  if (!existsSync(taxonomySrc)) {
    throw new Error(`taxonomy source not found at ${taxonomySrc} (set NOPE_API_DIR to the api checkout)`);
  }
  const taxonomy = parseTaxonomy(readFileSync(taxonomySrc, 'utf8'));
  const oversightTarget = join(OUT_DIR, 'oversight-taxonomy.ts');
  writeFileSync(oversightTarget, renderOversight(taxonomy, taxonomyRel, revision));
  const total = Object.values(taxonomy.codesByCategory).flat().length;
  console.log(`wrote ${oversightTarget}: ${taxonomy.categories.length} categories, ${total} codes`);

  const scopesRel = 'api/lib/resources/classificationToScopes.ts';
  const scopesSrc = join(API_DIR, 'lib', 'resources', 'classificationToScopes.ts');
  if (!existsSync(scopesSrc)) {
    throw new Error(`scopes source not found at ${scopesSrc} (set NOPE_API_DIR to the api checkout)`);
  }
  const scopesSource = readFileSync(scopesSrc, 'utf8');
  const scopes = parseConstObjectValues(scopesSource, 'SERVICE_SCOPES');
  const populations = parseConstObjectValues(scopesSource, 'POPULATIONS');
  const signpostTarget = join(OUT_DIR, 'signpost-taxonomy.ts');
  writeFileSync(signpostTarget, renderSignpost(scopes, populations, scopesRel, revision));
  console.log(`wrote ${signpostTarget}: ${scopes.length} scopes, ${populations.length} populations`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
